package ir

/*
Operation identifies a device.Backend kernel by the method it invokes.
Constants mirror the embedded interfaces on github.com/theapemachine/puter/device.Backend.
*/
type Operation uint8

const (
	OperationCountString Operation = iota + 1
	OperationCount8
	OperationCount16
	OperationCount32
	OperationCount64
	OperationExp
	OperationLog
	OperationLog1p
	OperationExpm1
	OperationSigmoid
	OperationLogSigmoid
	OperationTanh
	OperationSilu
	OperationSwish
	OperationGeluTanh
	OperationGelu
	OperationReLU
	OperationLeakyReLU
	OperationELU
	OperationCELU
	OperationSELU
	OperationSoftplus
	OperationMish
	OperationSoftsign
	OperationHardSigmoid
	OperationHardSwish
	OperationHardTanh
	OperationHardGelu
	OperationQuickGelu
	OperationTanhShrink
	OperationSoftmax
	OperationLogSoftmax
	OperationPReLU
	OperationPReLUV
	OperationLeakyReLUSlope
	OperationELUAlpha
	OperationCELUAlpha
	OperationThreshold
	OperationHardTanhRange
	OperationSnake
	OperationSnakeParametric
	OperationHardShrink
	OperationSoftShrink
	OperationRReLU
	OperationGLU
	OperationGeGLU
	OperationGeGLUTanh
	OperationSwiGLU
	OperationReGLU
	OperationSiGLU
	OperationGLUTensors
	OperationGeGLUTensors
	OperationGeGLUTanhTensors
	OperationSwiGLUTensors
	OperationReGLUTensors
	OperationSiGLUTensors
	OperationLinGLU
	OperationSeGLU
	OperationLinGLUTensors
	OperationSeGLUTensors
	OperationAdd
	OperationSub
	OperationMul
	OperationDiv
	OperationMax
	OperationMin
	OperationAbs
	OperationNeg
	OperationSqrt
	OperationAxpy
	OperationSum
	OperationProd
	OperationReduceMin
	OperationReduceMax
	OperationL1Norm
	OperationDot
	OperationMatmul
	OperationMaxPool2D
	OperationAvgPool2D
	OperationAdaptiveMaxPool2D
	OperationAdaptiveAvgPool2D
	OperationConv2D
	OperationConv1D
	OperationConv3D
	OperationConvTranspose2D
	OperationDropout
	OperationMSE
	OperationMAE
	OperationHuber
	OperationBinaryCrossEntropy
	OperationKLDivergence
	OperationCrossEntropy
	OperationGreedySample
	OperationTopKSample
	OperationTopPSample
	OperationLookup
	OperationBag
	OperationGroupNorm
	OperationInstanceNorm
	OperationBatchNormEval
	OperationLayerNorm
	OperationRMSNorm
	OperationRoPE
	OperationRoPEPairs
	OperationHawkesIntensity
	OperationHawkesKernelMatrix
	OperationHawkesLogLikelihood
	OperationMarkovMutualInformation
	OperationMarkovBlanketPartition
	OperationLaplacian
	OperationLaplacian4
	OperationGrad1D
	OperationDivergence1D
	OperationFFT1D
	OperationIFFT1D
	OperationQuantumPotential
	OperationBohmianVelocity
	OperationMadelungContinuity
	OperationCholesky
	OperationBackdoorAdjustment
	OperationFrontdoorAdjustment
	OperationDoIntervene
	OperationCATE
	OperationCounterfactual
	OperationIVEstimate
	OperationDAGMarkovFactorization
	OperationMarkovFlowActive
	OperationMarkovFlowInternal
	OperationApplyMask
	OperationCausalMask
	OperationALiBiBias
	OperationScaledDotProductAttention
	OperationFlashAttention
	OperationMultiHeadAttention
	OperationBind
	OperationBundle
	OperationPermute
	OperationInversePermute
	OperationSimilarity
	OperationFreeEnergy
	OperationExpectedFreeEnergy
	OperationBeliefUpdate
	OperationPrecisionWeight
	OperationPrediction
	OperationPredictionError
	OperationUpdateRepresentation
	OperationUpdateWeights
	OperationDequant
	OperationDequant4
	OperationQuant
)
